### ISSUE TITLE
Using template for php service

### ISSUE THREAD

**Issue by oanhnn** [AdrienPoupa/laradose#9]
I think you should use yaml extension fields for `php` service and `queue`, `horizon` service.
https://docs.docker.com/compose/compose-file/#extension-fields

```
version: '3.5'

# =========================================
# X-Templates
# =========================================
x-app-service: &app-service
  build:
    context: .
    args:
      PHP_VERSION: ${PHP_VERSION}
    dockerfile: ./docker/php/Dockerfile
  environment:
    PHP_VERSION: ${PHP_VERSION}
    PHP_IDE_CONFIG: "serverName=${PHP_SERVER_NAME}"
  volumes:
    - ./:/var/www
  user: "${USER_ID}:${GROUP_ID}"
  networks:
    - laravel

services:
  # ...

  php:
    <<: *app-service

  schedule:
    <<: *app-service
    working_dir: /var/www
    entrypoint: ['/var/www/artisan', 'queue:work']
```
